/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.formapagamentos;

import Model.ModelFormaPagamento;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static view.formapagamentos.jdGerenciarPagamento.JTConsultaPagamento;

/**
 *
 * @author Aluno TDS
 */
public class jdAlterarCartao extends javax.swing.JDialog {

    private boolean a = true;
    private boolean b = true;
    private boolean c = true;
    private boolean d = true;
    private boolean e = true;
    
    /**
     * Creates new form jdAlterarCartao
     */
    public jdAlterarCartao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNumero = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        txtNomeAlterar = new javax.swing.JTextField();
        txtNumeroCartaoAlterar = new javax.swing.JTextField();
        jlValidade = new javax.swing.JLabel();
        txtValidadeAlterar = new javax.swing.JTextField();
        jlCVV = new javax.swing.JLabel();
        txtCVV = new javax.swing.JTextField();
        jbAlterar = new javax.swing.JButton();
        jlValidade1 = new javax.swing.JLabel();
        jCBtipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlNumero.setText("Número do cartão");

        jlNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlNome.setText("Insira o nome impresso no cartão:");

        txtNomeAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlterarActionPerformed(evt);
            }
        });
        txtNomeAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeAlterarKeyReleased(evt);
            }
        });

        txtNumeroCartaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCartaoAlterarActionPerformed(evt);
            }
        });
        txtNumeroCartaoAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroCartaoAlterarKeyReleased(evt);
            }
        });

        jlValidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlValidade.setText("Validade:");

        txtValidadeAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValidadeAlterarActionPerformed(evt);
            }
        });
        txtValidadeAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValidadeAlterarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValidadeAlterarKeyTyped(evt);
            }
        });

        jlCVV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlCVV.setText("CVV:");

        txtCVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCVVActionPerformed(evt);
            }
        });
        txtCVV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCVVKeyReleased(evt);
            }
        });

        jbAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/check.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setEnabled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jlValidade1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlValidade1.setText("Selecione o tipo do cartão:");

        jCBtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Débito", "Crédito" }));
        jCBtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBtipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlValidade)
                                    .addComponent(txtValidadeAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCVV)
                                    .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNumeroCartaoAlterar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlNumero)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNomeAlterar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jlValidade1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBtipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroCartaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlValidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValidadeAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlCVV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jlValidade1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jbAlterar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAlterarActionPerformed

    private void txtNumeroCartaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCartaoAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCartaoAlterarActionPerformed

    private void txtValidadeAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValidadeAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValidadeAlterarActionPerformed

    private void txtCVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCVVActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
            Model.ModelFormaPagamento a = new ModelFormaPagamento();
            int codigo = (int) (JTConsultaPagamento.getValueAt(JTConsultaPagamento.getSelectedRow(), 0));
            
            a.setId(codigo);
            a.setNome(txtNomeAlterar.getText());
            a.setDescricao((String) jCBtipo.getSelectedItem());
            
            DAO.FormaPagamentoDAO.atualizar(a);
            JOptionPane.showMessageDialog(this, "Atualizado com Sucesso!");
            this.dispose();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jCBtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBtipoActionPerformed

    private void txtNomeAlterarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeAlterarKeyReleased
        // TODO add your handling code here:
        a = btnEnable("[a-zA-Z]+", txtNomeAlterar);
        enable();
    }//GEN-LAST:event_txtNomeAlterarKeyReleased

    private void txtNumeroCartaoAlterarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroCartaoAlterarKeyReleased
        // TODO add your handling code here:
        b = btnEnable("[0-9]+", txtNumeroCartaoAlterar);
        enable();
    }//GEN-LAST:event_txtNumeroCartaoAlterarKeyReleased

    private void txtValidadeAlterarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValidadeAlterarKeyReleased
        // TODO add your handling code here:
        c = btnEnable("[0-9]+", txtValidadeAlterar);
        enable();
    }//GEN-LAST:event_txtValidadeAlterarKeyReleased

    private void txtCVVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCVVKeyReleased
        // TODO add your handling code here:
        d = btnEnable("[0-9]+", txtValidadeAlterar);
        enable();
    }//GEN-LAST:event_txtCVVKeyReleased

    private void txtValidadeAlterarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValidadeAlterarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
       
        if(c != KeyEvent.VK_SLASH && !Character.isDigit(c)) {
           evt.consume();
        }
    }//GEN-LAST:event_txtValidadeAlterarKeyTyped

    
    
    private boolean btnEnable(String regex, JTextField abc) {
        String tx = abc.getText();
        if (tx.matches(regex)) {
            abc.setForeground(Color.black);
            return true;

        } else {
            abc.setForeground(Color.red);
            abc.requestFocus();
            return false;
        }
    }

    @Override
    public void enable() {
        if (a && b && c && d && e) {
            jbAlterar.setEnabled(true);
        } else {
            jbAlterar.setEnabled(false);
        }

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdAlterarCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdAlterarCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdAlterarCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdAlterarCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdAlterarCartao dialog = new jdAlterarCartao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBtipo;
    private static javax.swing.JButton jbAlterar;
    private javax.swing.JLabel jlCVV;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlValidade;
    private javax.swing.JLabel jlValidade1;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtNomeAlterar;
    private javax.swing.JTextField txtNumeroCartaoAlterar;
    private javax.swing.JTextField txtValidadeAlterar;
    // End of variables declaration//GEN-END:variables
}
