/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.formapagamentos;

import DAO.PedidoDAO;
import Model.ModelFormaPagamento;
import Model.ModelPedido;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import view.pedidos.JDialogPedidoCardapio;

/**
 *
 * @author João
 */
public class jdCadastrarPix extends javax.swing.JDialog {

    private boolean a = true;
    private boolean b = true;
    private boolean c = true;
    private boolean d = true;
    private boolean e = true;
    private JDialogPedidoCardapio jdPedidoCardapio;
    
    /**
     * Creates new form jdCadastrarPix
     */
    public jdCadastrarPix(java.awt.Frame parent, boolean modal, JDialogPedidoCardapio jdPedidoCardapio) {
        super(parent, modal);
        initComponents();
        this.jdPedidoCardapio = jdPedidoCardapio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbLimpar = new javax.swing.JButton();
        jlNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jlNumero = new javax.swing.JLabel();
        txtChavePix = new javax.swing.JTextField();
        jCBtipo = new javax.swing.JComboBox<>();
        jlValidade = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlNome.setText("Insira o nome completo do cliente:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });

        jlNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlNumero.setText("Chave pix:");

        txtChavePix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChavePixActionPerformed(evt);
            }
        });
        txtChavePix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChavePixKeyReleased(evt);
            }
        });

        jCBtipo.setEditable(true);
        jCBtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIX" }));
        jCBtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBtipoActionPerformed(evt);
            }
        });

        jlValidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlValidade.setText("PIX");

        jbSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/check.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlValidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBtipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtChavePix, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNumero)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlNome, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbSalvar)
                            .addGap(18, 18, 18)
                            .addComponent(jbLimpar)
                            .addGap(18, 18, 18))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChavePix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlValidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpar)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        txtNome.setText(null);
        txtChavePix.setText(null);
    }//GEN-LAST:event_jbLimparActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtChavePixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChavePixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChavePixActionPerformed

    private void jCBtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBtipoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        //Alterando o status do pagamento e do DB
        ModelPedido pedido = PedidoDAO.carregarUltimoPedido();
        pedido.setStatusPagamento(1); //tá pago
        pedido.setStatusPedido(2); //pedido finalizado
        PedidoDAO.atualizar(pedido); //atualiza o DB

            
        ModelFormaPagamento pagamento = new ModelFormaPagamento();

        pagamento.setNome(txtNome.getText());
        pagamento.setDescricao((String) jCBtipo.getSelectedItem());

        DAO.FormaPagamentoDAO.salvar(pagamento);
        JOptionPane.showMessageDialog(this, "Salvo com Sucesso!");
        this.dispose();
        jdPedidoCardapio.dispose();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        // TODO add your handling code here:
        a = btnEnable("[a-zA-Z]+", txtNome);
        enable();
    }//GEN-LAST:event_txtNomeKeyReleased

    private void txtChavePixKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChavePixKeyReleased
        // TODO add your handling code here:
        b = btnEnable("[0-9]+", txtChavePix);
        enable();
    }//GEN-LAST:event_txtChavePixKeyReleased

    
    private boolean btnEnable(String regex, JTextField abc) {
        String tx = abc.getText();
        if (tx.matches(regex)) {
            abc.setForeground(Color.black);
            return true;

        } else {
            abc.setForeground(Color.red);
            abc.requestFocus();
            return false;
        }
    }

    @Override
    public void enable() {
        if (a && b && c && d && e) {
            jbSalvar.setEnabled(true);
        } else {
            jbSalvar.setEnabled(false);
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdCadastrarPix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdCadastrarPix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdCadastrarPix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdCadastrarPix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*jdCadastrarPix dialog = new jdCadastrarPix(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBtipo;
    private javax.swing.JButton jbLimpar;
    private static javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlValidade;
    private javax.swing.JTextField txtChavePix;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
