/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.itensPedidos;

import DAO.ItensPedidoDAO;
import DAO.ProdutoDAO;
import Model.ModelItensPedido;
import Model.ModelPedido;
import Model.ProdutoModel;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import tablemodel.TableModelItensPedido;

/**
 *
 * @author Vaio
 */
public class JDCadastrarItensPedidos extends javax.swing.JDialog {
    private JTable tabela;
    private ModelPedido pedido;
    /**
     * Creates new form JDCadastrarItensPedidos
     */
    public JDCadastrarItensPedidos(java.awt.Frame parent, boolean modal, JTable tabela, ModelPedido pedido) {
        super(parent, modal);
        initComponents();
        this.pedido = pedido;
        this.tabela = tabela;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelQuantidade = new javax.swing.JLabel();
        jLabelProdutoID = new javax.swing.JLabel();
        jTextFieldProdutoID = new javax.swing.JTextField();
        jTextFieldOpcional = new javax.swing.JTextField();
        jButtonIncluir = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabelOpcional = new javax.swing.JLabel();
        jTextFieldQuantidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Incluir Item Pedido ERP Style");
        setPreferredSize(new java.awt.Dimension(290, 280));

        jLabelQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelQuantidade.setText("Quantidade:");

        jLabelProdutoID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelProdutoID.setText("Produto id:");

        jTextFieldProdutoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProdutoIDActionPerformed(evt);
            }
        });
        jTextFieldProdutoID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldProdutoIDKeyReleased(evt);
            }
        });

        jTextFieldOpcional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOpcionalActionPerformed(evt);
            }
        });
        jTextFieldOpcional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldOpcionalKeyReleased(evt);
            }
        });

        jButtonIncluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/check.png"))); // NOI18N
        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabelOpcional.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelOpcional.setText("Opcional:");

        jTextFieldQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantidadeActionPerformed(evt);
            }
        });
        jTextFieldQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldQuantidadeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButtonIncluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelProdutoID, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(jTextFieldProdutoID)
                                .addComponent(jLabelOpcional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldQuantidade)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelProdutoID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldProdutoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabelQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOpcional)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonLimpar))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProdutoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProdutoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProdutoIDActionPerformed

    private void jTextFieldOpcionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOpcionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOpcionalActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        int quantidade = Integer.parseInt(jTextFieldQuantidade.getText());
        int id = Integer.parseInt(jTextFieldProdutoID.getText());
        String opcional = jTextFieldOpcional.getText();
                
        ModelItensPedido itemPedido = new ModelItensPedido();
        
        ProdutoDAO produtoDAO = new ProdutoDAO();
        itemPedido.setProdutoId(produtoDAO.obterProdutoPorID(id));
        
        itemPedido.setPedidoId(pedido);
        
        itemPedido.setQuantidade(quantidade);
        itemPedido.setOpcional(opcional);
        
        //itensPedidoDAO.salvar(itemPedido);
        ItensPedidoDAO.salvar(itemPedido);
        
        //JDialogPedidoCardapio.itemsPedido.add(itemPedido);
        //this.dispose();
        limparTela();
        
        TableModelItensPedido tableModel = new TableModelItensPedido(ItensPedidoDAO.carregarItensDoPedido(pedido.getId()));
        tabela.setModel(tableModel);
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldProdutoID.setText(null);
        jTextFieldOpcional.setText(null);
        jTextFieldQuantidade.setText(null);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void limparTela()
    {
        jTextFieldProdutoID.setText(null);
        jTextFieldOpcional.setText(null);
        jTextFieldQuantidade.setText(null);  
        jTextFieldProdutoID.requestFocus();
    }
    
    private void jTextFieldProdutoIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProdutoIDKeyReleased
        /*verificacaoPedidoId = validacao("\\d+", jTextFieldProdutoID);
        visibilidade();*/
    }//GEN-LAST:event_jTextFieldProdutoIDKeyReleased

    private void jTextFieldOpcionalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOpcionalKeyReleased
       /* verificacaoProdutoId = validacao("\\d+", jTextFieldQuantidade);
        visibilidade();*/
    }//GEN-LAST:event_jTextFieldOpcionalKeyReleased

    private void jTextFieldQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantidadeActionPerformed

    private void jTextFieldQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantidadeKeyReleased
    
    /*private boolean verificacaoPedidoId;
    private boolean verificacaoProdutoId;
    private boolean verificacaoQuantidade;
    
    private void visibilidade(){
        if (verificacaoPedidoId && verificacaoProdutoId && verificacaoQuantidade){
            jButtonIncluir.setEnabled(true);
        } else {
            jButtonIncluir.setEnabled(false);
        }
    }*/
    
    /*private boolean validacao(String letrinha, JTextField field){
        String texto = field.getText();
        
        if(texto.matches(letrinha)){
            field.setForeground(Color.blue);
            return true;
        } else {
            field.setForeground(Color.red);
            field.requestFocus();
            return false;
        }
    } */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDCadastrarItensPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDCadastrarItensPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDCadastrarItensPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDCadastrarItensPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*JDCadastrarItensPedidos dialog = new JDCadastrarItensPedidos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabelOpcional;
    private javax.swing.JLabel jLabelProdutoID;
    private javax.swing.JLabel jLabelQuantidade;
    private javax.swing.JTextField jTextFieldOpcional;
    private javax.swing.JTextField jTextFieldProdutoID;
    private javax.swing.JTextField jTextFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
