package view.itensPedidos;

import DAO.CategoriaProdutoDAO;
import DAO.ItensPedidoDAO;
import DAO.ProdutoDAO;
import Model.ModelCategoriaProduto;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import tablemodel.TableModelProduto;
import org.jdesktop.swingx.prompt.PromptSupport;
import tablemodel.TableModelVenda;


public class JDialogRelatorioVendas extends javax.swing.JDialog 
{
    
    private String filtroCategoria = "%";
    private String filtroNome = "%";
    private int ordenacao = 0;
    ArrayList<ModelCategoriaProduto> categorias;
    
    public JDialogRelatorioVendas(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        jTableVendas.setModel(initTable());
        //jTableVendas.setAutoCreateRowSorter(true);
        carregarCategorias();
        ajustarTamanhoTabela();
        this.setLocationRelativeTo(null);
        
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(jRadioButtonOrdenarQtde);
        buttonGroup.add(jRadioButtonOrdenarValor);
    }
    
    private TableModelVenda initTable() 
    {
        return new TableModelVenda(ItensPedidoDAO.ordenarMaisVendidos(filtroCategoria, filtroNome));
    }

    public void ajustarTamanhoTabela() //ver depois
    {
        jTableVendas.setRowHeight(25);
        
        TableColumn colunaID = jTableVendas.getColumnModel().getColumn(1);
        colunaID.setPreferredWidth(420);
        colunaID.setMaxWidth(450);
        
        /*TableColumn colunaPreco = jTableVendas.getColumnModel().getColumn(2);
        colunaPreco.setPreferredWidth(120);
        colunaPreco.setMaxWidth(120);*/

        atualizarTamanhoTabela();
    }
    
    public void atualizarTamanhoTabela()
    {
        Dimension size = new Dimension(500, jTableVendas.getRowCount() * jTableVendas.getRowHeight());
        jTableVendas.setPreferredScrollableViewportSize(size);
        jTableVendas.setPreferredSize(size);
    }

    private void carregarCategorias() 
    {
        categorias = new ArrayList<>();
        
        categorias = CategoriaProdutoDAO.obterTodasCategorias();
        
        for(int i = 0; i < categorias.size(); i++) 
        {
            String idCategoria = String.valueOf(categorias.get(i).getId());
            String descricao = categorias.get(i).getDescricao();
            String item = idCategoria + " - " + descricao;
            this.jComboBoxCategoriaProduto.addItem(item);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTableVendas = new javax.swing.JTable();
        jComboBoxCategoriaProduto = new javax.swing.JComboBox<>();
        jTextFieldFiltrarNomeProduto = new javax.swing.JTextField();
        jButtonLimparFiltrosProduto = new javax.swing.JButton();
        jLabelQtdeTotal = new javax.swing.JLabel();
        jLabelValorTotal = new javax.swing.JLabel();
        jRadioButtonOrdenarQtde = new javax.swing.JRadioButton();
        jRadioButtonOrdenarValor = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas");
        setMinimumSize(new java.awt.Dimension(1000, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Vendas por Itens");
        jLabelTitulo.setMinimumSize(new java.awt.Dimension(1000, 680));
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 12, 400, -1));

        jScrollPane.setPreferredSize(new java.awt.Dimension(1000, 550));

        jTableVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID do Produto", "Nome do Produto", "Quantidade Vendida", "Total Vendido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVendas.setIntercellSpacing(new java.awt.Dimension(20, 10));
        jTableVendas.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jTableVendas.setPreferredSize(new java.awt.Dimension(800, 200));
        jTableVendas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane.setViewportView(jTableVendas);

        getContentPane().add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 120, 950, 500));

        jComboBoxCategoriaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar por Categoria" }));
        jComboBoxCategoriaProduto.setMinimumSize(new java.awt.Dimension(65, 22));
        jComboBoxCategoriaProduto.setPreferredSize(new java.awt.Dimension(65, 25));
        jComboBoxCategoriaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCategoriaProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, -1));

        jTextFieldFiltrarNomeProduto.setPreferredSize(new java.awt.Dimension(64, 25));
        jTextFieldFiltrarNomeProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFiltrarNomeProdutoKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldFiltrarNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 240, -1));
        PromptSupport.setPrompt("Filtrar por Nome", jTextFieldFiltrarNomeProduto);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, jTextFieldFiltrarNomeProduto);

        jButtonLimparFiltrosProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tchefood/src/icon/filtro-limpo.png"))); // NOI18N
        jButtonLimparFiltrosProduto.setText("Limpar");
        jButtonLimparFiltrosProduto.setPreferredSize(new java.awt.Dimension(90, 25));
        jButtonLimparFiltrosProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparFiltrosProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimparFiltrosProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        jLabelQtdeTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelQtdeTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQtdeTotal.setText("Quantidade Total:");
        jLabelQtdeTotal.setMinimumSize(new java.awt.Dimension(1000, 680));
        getContentPane().add(jLabelQtdeTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 92, 200, -1));

        jLabelValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValorTotal.setText("Valor Total:");
        jLabelValorTotal.setMinimumSize(new java.awt.Dimension(1000, 680));
        getContentPane().add(jLabelValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 92, 200, -1));

        jRadioButtonOrdenarQtde.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButtonOrdenarQtde.setSelected(true);
        jRadioButtonOrdenarQtde.setText("Ordenar por Quantidade");
        jRadioButtonOrdenarQtde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOrdenarQtdeActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonOrdenarQtde, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 60, -1, -1));

        jRadioButtonOrdenarValor.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButtonOrdenarValor.setText("Ordenar por Total");
        jRadioButtonOrdenarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOrdenarValorActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonOrdenarValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFiltrarNomeProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFiltrarNomeProdutoKeyReleased
        this.filtrar();
    }//GEN-LAST:event_jTextFieldFiltrarNomeProdutoKeyReleased

    private void jButtonLimparFiltrosProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparFiltrosProdutoActionPerformed
        this.limparFiltros();
    }//GEN-LAST:event_jButtonLimparFiltrosProdutoActionPerformed

    private void jComboBoxCategoriaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaProdutoActionPerformed
        // TODO add your handling code here:
        this.filtrar();
    }//GEN-LAST:event_jComboBoxCategoriaProdutoActionPerformed

    private void jRadioButtonOrdenarQtdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOrdenarQtdeActionPerformed
        // TODO add your handling code here:
        ordenacao = 0;
        this.filtrar();
    }//GEN-LAST:event_jRadioButtonOrdenarQtdeActionPerformed

    private void jRadioButtonOrdenarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOrdenarValorActionPerformed
        // TODO add your handling code here:
        ordenacao = 1;
        this.filtrar();
    }//GEN-LAST:event_jRadioButtonOrdenarValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                JDialogRelatorioVendas dialog = new JDialogRelatorioVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() 
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) 
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimparFiltrosProduto;
    private javax.swing.JComboBox<String> jComboBoxCategoriaProduto;
    public static javax.swing.JLabel jLabelQtdeTotal;
    private javax.swing.JLabel jLabelTitulo;
    public static javax.swing.JLabel jLabelValorTotal;
    private javax.swing.JRadioButton jRadioButtonOrdenarQtde;
    private javax.swing.JRadioButton jRadioButtonOrdenarValor;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTableVendas;
    private javax.swing.JTextField jTextFieldFiltrarNomeProduto;
    // End of variables declaration//GEN-END:variables



    private void filtrar()
    {
        if(jComboBoxCategoriaProduto.getSelectedIndex() > 0)
        {
            int idDaCategoria = categorias.get(jComboBoxCategoriaProduto.getSelectedIndex() -1 ).getId(); //pq começa em 0 o array

            filtroCategoria = String.valueOf(idDaCategoria);
        }
        else
        {
            filtroCategoria = "%";
        }
        if(!jTextFieldFiltrarNomeProduto.getText().isBlank())
        {
            //filtroNome = "%" + jTextFieldFiltrarNomeProduto.getText() + "%";
            filtroNome = jTextFieldFiltrarNomeProduto.getText();
        }
        else
        {
            filtroNome = "%";
        }
        

        if(ordenacao == 0)
        {
            TableModelVenda tableModel = new TableModelVenda(ItensPedidoDAO.ordenarMaisVendidos(filtroCategoria, filtroNome));
            jTableVendas.setModel(tableModel);
        }
        else
        {
            TableModelVenda tableModel = new TableModelVenda(ItensPedidoDAO.ordenarMaisValor(filtroCategoria, filtroNome));
            jTableVendas.setModel(tableModel);
        }
        
        ajustarTamanhoTabela();
    }
    
    private void limparFiltros()
    {
        jComboBoxCategoriaProduto.setSelectedIndex(0);
        jTextFieldFiltrarNomeProduto.setText(null);
        filtroCategoria = "%";
        filtroNome = "%";
        //ordenacao = 1;

        if(ordenacao == 0)
        {
            TableModelVenda tableModel = new TableModelVenda(ItensPedidoDAO.ordenarMaisVendidos(filtroCategoria, filtroNome));
            jTableVendas.setModel(tableModel);
        }
        else
        {
            TableModelVenda tableModel = new TableModelVenda(ItensPedidoDAO.ordenarMaisValor(filtroCategoria, filtroNome));
            jTableVendas.setModel(tableModel);
        }
        
        ajustarTamanhoTabela();
    }
}
