package view.itensPedidos;

import view.produto.*;
import DAO.CategoriaProdutoDAO;
import DAO.ItensPedidoDAO;
import DAO.ProdutoDAO;
import Model.ModelCategoriaProduto;
import Model.ProdutoModel;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import tablemodel.TableModelProduto;
import org.jdesktop.swingx.prompt.PromptSupport;
import tablemodel.TableModelItensPedido;
import tablemodel.TableModelItensPedidoLista;


public class JDialogGerenciarItemPedido extends javax.swing.JDialog 
{
     
    public JDialogGerenciarItemPedido(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        jTableItensPedido.setModel(initTable());
        jTableItensPedido.setRowHeight(25);
        atualizarTamanhoTabela();
        this.setLocationRelativeTo(null);
    }
    
    private TableModelItensPedidoLista initTable() 
    {
        return new TableModelItensPedidoLista(ItensPedidoDAO.obterTodos());
    }


    public void atualizarTamanhoTabela()
    {
        Dimension size = new Dimension(500, jTableItensPedido.getRowCount() * jTableItensPedido.getRowHeight());
        jTableItensPedido.setPreferredScrollableViewportSize(size);
        jTableItensPedido.setPreferredSize(size);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTableItensPedido = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listagem");
        setMinimumSize(new java.awt.Dimension(1000, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Lista Itens de Pedidos");
        jLabelTitulo.setMinimumSize(new java.awt.Dimension(1000, 680));
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 12, 400, -1));

        jScrollPane.setPreferredSize(new java.awt.Dimension(1000, 550));

        jTableItensPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Pedido ID", "Produto ID", "Quantidade", "Opcional"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableItensPedido.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jTableItensPedido.setPreferredSize(new java.awt.Dimension(800, 200));
        jTableItensPedido.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane.setViewportView(jTableItensPedido);
        if (jTableItensPedido.getColumnModel().getColumnCount() > 0) {
            jTableItensPedido.getColumnModel().getColumn(0).setResizable(false);
            jTableItensPedido.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        getContentPane().add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 120, 950, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogGerenciarItemPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogGerenciarItemPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogGerenciarItemPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogGerenciarItemPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                JDialogGerenciarItemPedido dialog = new JDialogGerenciarItemPedido(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() 
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) 
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTableItensPedido;
    // End of variables declaration//GEN-END:variables

}
