/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.usuario;

import Model.ModelUsuario;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import static view.usuario.jdGerenciarUsuario.JTConsulta;


/**
 *
 * @author adriano
 */
public class jdAlterarDados extends javax.swing.JDialog {

    private boolean a = true;
    private boolean b = true;
    private boolean c = true;
    private boolean d = true;
    private boolean e = true;

    /**
     * Creates new form jdAlterarDados
     */
    public jdAlterarDados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAlterarusuarioNome = new javax.swing.JTextField();
        txtAlterarusuarioEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAlterarusuarioSenha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAlterarusuarioPapel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbAlterar = new javax.swing.JButton();
        txtAlterarusuarioTelefone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualizar Usuarios");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");

        txtAlterarusuarioNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAlterarusuarioNomeFocusLost(evt);
            }
        });
        txtAlterarusuarioNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlterarusuarioNomeKeyReleased(evt);
            }
        });

        txtAlterarusuarioEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlterarusuarioEmailActionPerformed(evt);
            }
        });
        txtAlterarusuarioEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlterarusuarioEmailKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nova Senha:");

        txtAlterarusuarioSenha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAlterarusuarioSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAlterarusuarioSenhaFocusGained(evt);
            }
        });
        txtAlterarusuarioSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlterarusuarioSenhaActionPerformed(evt);
            }
        });
        txtAlterarusuarioSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlterarusuarioSenhaKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Papel:");

        txtAlterarusuarioPapel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAlterarusuarioPapelFocusLost(evt);
            }
        });
        txtAlterarusuarioPapel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlterarusuarioPapelKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Telefone:");

        jbAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/check.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setEnabled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        txtAlterarusuarioTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlterarusuarioTelefoneKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAlterarusuarioNome)
                            .addComponent(txtAlterarusuarioEmail)
                            .addComponent(txtAlterarusuarioSenha)
                            .addComponent(txtAlterarusuarioPapel)
                            .addComponent(txtAlterarusuarioTelefone)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlterarusuarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlterarusuarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlterarusuarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlterarusuarioPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlterarusuarioTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAlterar)
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAlterarusuarioEmail, txtAlterarusuarioNome, txtAlterarusuarioPapel, txtAlterarusuarioSenha, txtAlterarusuarioTelefone});

        txtAlterarusuarioNome.setBorder(BorderFactory.createLineBorder(new Color(68,192,85)));
        txtAlterarusuarioEmail.setBorder(BorderFactory.createLineBorder(new Color(68,192,85)));
        txtAlterarusuarioPapel.setBorder(BorderFactory.createLineBorder(new Color(68,192,85)));
        txtAlterarusuarioTelefone.setBorder(BorderFactory.createLineBorder(new Color(68,192,85)));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed

        Model.ModelUsuario a = new ModelUsuario();
        int codigo = (int) (JTConsulta.getValueAt(JTConsulta.getSelectedRow(), 0));

        String senhaOriginal = txtAlterarusuarioSenha.getText();

        a.setId(codigo);

        a.setNome(txtAlterarusuarioNome.getText());

        a.setEmail(txtAlterarusuarioEmail.getText());

        try {
            a.setSenha(jdcadastrarUsuario.Cripto(senhaOriginal));
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(jdAlterarDados.class.getName()).log(Level.SEVERE, null, ex);
        }

        a.setPapel(txtAlterarusuarioPapel.getText());

        a.setTelefone(txtAlterarusuarioTelefone.getText());

        try {
            DAO.DAOUsuario.update(a);
            JOptionPane.showMessageDialog(this, "Atualizado com Sucesso!");
            this.dispose();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(jdAlterarDados.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jbAlterarActionPerformed

    private void txtAlterarusuarioNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlterarusuarioNomeFocusLost
        // TODO add your handling code here:


    }//GEN-LAST:event_txtAlterarusuarioNomeFocusLost

    private void txtAlterarusuarioPapelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlterarusuarioPapelFocusLost
        // TODO add your handling code here:


    }//GEN-LAST:event_txtAlterarusuarioPapelFocusLost


    private void txtAlterarusuarioNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlterarusuarioNomeKeyReleased
        // TODO add your handling code here:

        a = btnEnable("^(?U)[\\p{L}\\s]+$", txtAlterarusuarioNome);
        enable();
    }//GEN-LAST:event_txtAlterarusuarioNomeKeyReleased

    private void txtAlterarusuarioPapelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlterarusuarioPapelKeyReleased
        // TODO add your handling code here:

        b = btnEnable("^(?U)[\\p{L}\\s]+$", txtAlterarusuarioPapel);
        enable();
    }//GEN-LAST:event_txtAlterarusuarioPapelKeyReleased

    private void txtAlterarusuarioEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlterarusuarioEmailKeyReleased

        d = !txtAlterarusuarioEmail.getText().isEmpty();
        enable();
    }//GEN-LAST:event_txtAlterarusuarioEmailKeyReleased

    private void txtAlterarusuarioSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlterarusuarioSenhaKeyReleased
        // TODO add your handling code here:
     
       if(!txtAlterarusuarioSenha.getText().isEmpty()){
            txtAlterarusuarioSenha.setBorder(BorderFactory.createLineBorder(new Color(68,192,85)));
       }else{
            txtAlterarusuarioSenha.setBorder(BorderFactory.createLineBorder(Color.RED));
       }
       

        e = !txtAlterarusuarioSenha.getText().isEmpty();

        enable();
    }//GEN-LAST:event_txtAlterarusuarioSenhaKeyReleased

    private void txtAlterarusuarioTelefoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlterarusuarioTelefoneKeyReleased
        c = btnEnable("[0-9]+", txtAlterarusuarioTelefone);
        enable();
    }//GEN-LAST:event_txtAlterarusuarioTelefoneKeyReleased

    private void txtAlterarusuarioSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlterarusuarioSenhaFocusGained
        // TODO add your handling code here:
        e = false;
    }//GEN-LAST:event_txtAlterarusuarioSenhaFocusGained

    private void txtAlterarusuarioEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlterarusuarioEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlterarusuarioEmailActionPerformed

    private void txtAlterarusuarioSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlterarusuarioSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlterarusuarioSenhaActionPerformed

    private boolean btnEnable(String regex, JTextField abc) {
        String tx = abc.getText();
        if (tx.matches(regex)) {
            abc.setForeground(Color.black);
            abc.setBorder(BorderFactory.createLineBorder(new Color(68,192,85)));
            return true;

        } else {
            abc.setForeground(Color.red);
            abc.setBorder(BorderFactory.createLineBorder(Color.RED));
            abc.requestFocus();
            return false;
        }
    }

    @Override
    public void enable() {
        if (a && b && c && d && e) {
            jbAlterar.setEnabled(true);
        } else {
            jbAlterar.setEnabled(false);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdAlterarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdAlterarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdAlterarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdAlterarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdAlterarDados dialog = new jdAlterarDados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private static javax.swing.JButton jbAlterar;
    public static javax.swing.JTextField txtAlterarusuarioEmail;
    public static javax.swing.JTextField txtAlterarusuarioNome;
    public static javax.swing.JTextField txtAlterarusuarioPapel;
    public static javax.swing.JTextField txtAlterarusuarioSenha;
    public static javax.swing.JTextField txtAlterarusuarioTelefone;
    // End of variables declaration//GEN-END:variables
}
