/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.usuario;

import org.jdesktop.swingx.prompt.PromptSupport;

import static DAO.DAOUsuario.isIdValido;
import Model.ModelUsuario;
import com.toedter.calendar.JCalendar;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import view.JFRMenu;
import static view.usuario.jdAlterarDados.*;

/**
 *
 * @author adriano
 */
public class jdGerenciarUsuario extends javax.swing.JDialog {

    String data = "";
    String opcao = "";

    /**
     * Creates new form jdGerenciarUsuario
     */
    public jdGerenciarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTConsulta = new javax.swing.JTable();
        jbExcluir = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        jbAlterar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento Usuarios");

        JTConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JTConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Email", "Senha", "Papel", "Telefone", "Criacao", "Alteracao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTConsulta);
        if (JTConsulta.getColumnModel().getColumnCount() > 0) {
            JTConsulta.getColumnModel().getColumn(0).setResizable(false);
            JTConsulta.getColumnModel().getColumn(1).setResizable(false);
            JTConsulta.getColumnModel().getColumn(3).setResizable(false);
            JTConsulta.getColumnModel().getColumn(4).setResizable(false);
        }

        jbExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clean.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jbAlterar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/paper.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setEnabled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jButton3.setText("Pesquisar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nome", "Email", "Telefone", "Papel", "Telefone", "Data Criacao" }));
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir)))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton3, jbAlterar, jbExcluir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExcluir)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAlterar)
                    .addComponent(jButton3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        PromptSupport.setPrompt("Pesquisar ...", txtPesquisar);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, txtPesquisar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed

        try {
            //exclui linha do banco de dados
            int codigo = (int) (JTConsulta.getValueAt(JTConsulta.getSelectedRow(), 0));
            //excluir linha da tabela
            ((DefaultTableModel) JTConsulta.getModel()).removeRow(JTConsulta.getSelectedRow());

            String nome;

            ModelUsuario a = new ModelUsuario();
            a.setId(codigo);
            nome = DAO.DAOUsuario.nomeUsuario(codigo);
            DAO.DAOUsuario.deletar(a);
            JOptionPane.showMessageDialog(this, "Excluido com Sucesso " + nome);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(jdGerenciarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:

        jdAlterarDados a = new jdAlterarDados(null, true);

        int selectedRowIndex = JTConsulta.getSelectedRow();

        String nome = (String) JTConsulta.getValueAt(selectedRowIndex, 1);
        String email = (String) JTConsulta.getValueAt(selectedRowIndex, 2);
        //String senha = (String) JTConsulta.getValueAt(selectedRowIndex, 3);
        String papel = (String) JTConsulta.getValueAt(selectedRowIndex, 4);
        String telefone = (String) JTConsulta.getValueAt(selectedRowIndex, 5);
        txtAlterarusuarioNome.setText(nome);
        txtAlterarusuarioEmail.setText(email);
        txtAlterarusuarioSenha.requestFocus();
        txtAlterarusuarioPapel.setText(papel);
        txtAlterarusuarioTelefone.setText(telefone);
        
              
      
      
txtAlterarusuarioSenha.setBorder(BorderFactory.createLineBorder(Color.RED));

        a.setVisible(true);

    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     

            String a = txtPesquisar.getText();
           
     
        try {
            // TODO add your handling code here:

            ArrayList<ModelUsuario> dwd = DAO.DAOUsuario.consultar(a);

            if (dwd.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nao Ha usuarios cadastrados");
                this.dispose();
            } else {

                jbAlterar.setEnabled(true);

                jbExcluir.setEnabled(true);

                DefaultTableModel modelo = (DefaultTableModel) JTConsulta.getModel();

                modelo.setNumRows(0);

                try {
                    for (Model.ModelUsuario m : DAO.DAOUsuario.consultar(a)) {
                        modelo.addRow(new Object[]{
                            m.getId(), m.getNome(), m.getEmail(), m.getSenha(), m.getPapel(), m.getTelefone(), m.getDataCriacao(), m.getDataAtualizacao()

                        });
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(JFRMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
                JTConsulta.setModel(modelo);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(jdGerenciarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jComboBox1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdGerenciarUsuario dialog = new jdGerenciarUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable JTConsulta;
    private javax.swing.JButton jButton3;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
